#services are the containers that will be created.
services:
#this is the name of our app container.
  web:
  #This builds the image from the Dockerfile in the current directory auto.
    build: .
    #We can override the cmd in the Dockerfile.
    # command: python manage.py runserver 0.0.0.0:8000
    # This makes any change in the code to be copied automatically in the container.
    volumes:
      - .:/app
    ports:
      - "8000:8000"
      # this means the web container to wait for the database to be ready before starting.
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    env_file:
      - .env
      #this is a named volume that will persist the data.
    volumes:
      - postgres_data:/var/lib/postgresql/data/
       
    ports:
      - "5432:5432"

  django-redis:  
    image: redis
    ports:
      - "6379:6379"  
      #auto restart the container if it stops.
    restart: always
    volumes:
      - redis_data:/data

  celery:
    build: .
    command: celery -A backend worker --loglevel=info
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - web
      - django-redis
      - db
    env_file:
      - .env

volumes:
  postgres_data:
  redis_data: